// seed.go
package main

import "gorm.io/gorm"

func Products(db *gorm.DB) {
	products := []Product{
		{
			Name:        "Premium Maize Seeds",
			Category:    "Seeds",
			Description: "High-yield hybrid maize seeds suitable for various climates",
			Price:       799.99,
			Stock:       1000,
			ImageURL:    "/images/products/maize-seeds.jpg",
			Brand:       "Pioneer",
			Unit:        "kg",
			Rating:      4.8,
			Reviews:     156,
		},
		{
			Name:        "NPK Fertilizer",
			Category:    "Fertilizers",
			Description: "Balanced NPK 17-17-17 fertilizer for all-purpose use",
			Price:       2499.99,
			Stock:       500,
			ImageURL:    "/images/products/npk-fertilizer.jpg",
			Brand:       "GrowMore",
			Unit:        "50kg",
			Rating:      4.9,
			Reviews:     203,
		},
		{
			Name:        "Organic Pesticide",
			Category:    "Pesticides",
			Description: "Natural pest control solution safe for organic farming",
			Price:       999.99,
			Stock:       300,
			ImageURL:    "/images/products/organic-pesticide.jpg",
			Brand:       "EcoGuard",
			Unit:        "5L",
			Rating:      4.6,
			Reviews:     89,
		},
		{
			Name:        "Garden Hand Tools Set",
			Category:    "Tools",
			Description: "Complete set of essential garden tools",
			Price:       1499.99,
			Stock:       150,
			ImageURL:    "/images/products/garden-tools.jpg",
			Brand:       "FarmPro",
			Unit:        "set",
			Rating:      4.7,
			Reviews:     167,
		},
		{
			Name:        "Tomato Seeds",
			Category:    "Seeds",
			Description: "High-yielding determinate tomato variety",
			Price:       299.99,
			Stock:       800,
			ImageURL:    "/images/products/tomato-seeds.jpg",
			Brand:       "SeedCo",
			Unit:        "100g",
			Rating:      4.5,
			Reviews:     94,
		},
	   {
		Name:        "Premium Wheat Seeds",
		Category:    "Fertilizers",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       4939.48,
		Stock:       273,
		ImageURL:    "/images/products/product-916.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      1.7,
		Reviews:     351,
	  },
	  {
		Name:        "Advanced Rice Seeds",
		Category:    "Tools",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       3900.68,
		Stock:       135,
		ImageURL:    "/images/products/product-917.jpg",
		Brand:       "Pioneer",
		Unit:        "Set",
		Rating:      4.9,
		Reviews:     419,
	  },
	  {
		Name:        "High-Yield Rice Seeds",
		Category:    "Pesticides",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       4645.84,
		Stock:       799,
		ImageURL:    "/images/products/product-918.jpg",
		Brand:       "EcoGuard",
		Unit:        "Kg",
		Rating:      2.1,
		Reviews:     264,
	  },
	  {
		Name:        "High-Yield Potato Seeds",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       3279.38,
		Stock:       291,
		ImageURL:    "/images/products/product-919.jpg",
		Brand:       "EcoGuard",
		Unit:        "Kg",
		Rating:      4.4,
		Reviews:     8,
	  },
	  {
		Name:        "Eco-Friendly Maize Seeds",
		Category:    "Tools",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       1602.45,
		Stock:       253,
		ImageURL:    "/images/products/product-920.jpg",
		Brand:       "SeedCo",
		Unit:        "Kg",
		Rating:      2.5,
		Reviews:     103,
	  },
	  {
		Name:        "Organic Wheat Seeds",
		Category:    "Tools",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       1990.01,
		Stock:       742,
		ImageURL:    "/images/products/product-921.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      3.5,
		Reviews:     162,
	  },
	  {
		Name:        "Eco-Friendly Organic Pesticide",
		Category:    "Fertilizers",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       527.89,
		Stock:       717,
		ImageURL:    "/images/products/product-922.jpg",
		Brand:       "SeedCo",
		Unit:        "100g",
		Rating:      2.8,
		Reviews:     306,
	  },
	  {
		Name:        "High-Yield Tomato Seeds",
		Category:    "Fertilizers",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       2500.36,
		Stock:       537,
		ImageURL:    "/images/products/product-923.jpg",
		Brand:       "EcoGuard",
		Unit:        "5L",
		Rating:      1.2,
		Reviews:     342,
	  },
	  {
		Name:        "Premium NPK Fertilizer",
		Category:    "Fertilizers",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       2832.02,
		Stock:       820,
		ImageURL:    "/images/products/product-924.jpg",
		Brand:       "EcoGuard",
		Unit:        "Kg",
		Rating:      3.1,
		Reviews:     497,
	  },
	  {
		Name:        "High-Yield Rice Seeds",
		Category:    "Tools",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       3034.08,
		Stock:       428,
		ImageURL:    "/images/products/product-925.jpg",
		Brand:       "EcoGuard",
		Unit:        "100g",
		Rating:      3.5,
		Reviews:     10,
	  },
	  {
		Name:        "Eco-Friendly Organic Pesticide",
		Category:    "Fertilizers",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       225.45,
		Stock:       685,
		ImageURL:    "/images/products/product-926.jpg",
		Brand:       "GrowMore",
		Unit:        "100g",
		Rating:      4.9,
		Reviews:     146,
	  },
	  {
		Name:        "Advanced Organic Pesticide",
		Category:    "Tools",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       753.80,
		Stock:       815,
		ImageURL:    "/images/products/product-927.jpg",
		Brand:       "EcoGuard",
		Unit:        "100g",
		Rating:      4.8,
		Reviews:     482,
	  },
	  {
		Name:        "High-Yield Wheat Seeds",
		Category:    "Seeds",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2491.04,
		Stock:       688,
		ImageURL:    "/images/products/product-928.jpg",
		Brand:       "GrowMore",
		Unit:        "5L",
		Rating:      1.0,
		Reviews:     377,
	  },
	  {
		Name:        "Advanced Potato Seeds",
		Category:    "Seeds",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       3643.88,
		Stock:       187,
		ImageURL:    "/images/products/product-929.jpg",
		Brand:       "SeedCo",
		Unit:        "100g",
		Rating:      4.4,
		Reviews:     338,
	  },
	  {
		Name:        "High-Yield Tomato Seeds",
		Category:    "Pesticides",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       4514.94,
		Stock:       704,
		ImageURL:    "/images/products/product-930.jpg",
		Brand:       "GrowMore",
		Unit:        "Set",
		Rating:      4.6,
		Reviews:     15,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Seeds",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       3787.57,
		Stock:       671,
		ImageURL:    "/images/products/product-931.jpg",
		Brand:       "EcoGuard",
		Unit:        "5L",
		Rating:      1.5,
		Reviews:     136,
	  },
	  {
		Name:        "Advanced Rice Seeds",
		Category:    "Seeds",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       4384.18,
		Stock:       953,
		ImageURL:    "/images/products/product-932.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      1.5,
		Reviews:     339,
	  },
	  {
		Name:        "Eco-Friendly Tomato Seeds",
		Category:    "Tools",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       3733.80,
		Stock:       567,
		ImageURL:    "/images/products/product-933.jpg",
		Brand:       "FarmPro",
		Unit:        "50kg",
		Rating:      2.0,
		Reviews:     37,
	  },
	  {
		Name:        "Organic Wheat Seeds",
		Category:    "Pesticides",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       861.83,
		Stock:       743,
		ImageURL:    "/images/products/product-934.jpg",
		Brand:       "SeedCo",
		Unit:        "50kg",
		Rating:      3.5,
		Reviews:     223,
	  },
	  {
		Name:        "High-Yield Potato Seeds",
		Category:    "Fertilizers",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4423.12,
		Stock:       704,
		ImageURL:    "/images/products/product-935.jpg",
		Brand:       "Pioneer",
		Unit:        "Set",
		Rating:      1.8,
		Reviews:     486,
	  },
	  {
		Name:        "Advanced Tomato Seeds",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       4561.01,
		Stock:       533,
		ImageURL:    "/images/products/product-936.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      2.6,
		Reviews:     302,
	  },
	  {
		Name:        "Eco-Friendly Maize Seeds",
		Category:    "Pesticides",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       1625.88,
		Stock:       580,
		ImageURL:    "/images/products/product-937.jpg",
		Brand:       "SeedCo",
		Unit:        "50kg",
		Rating:      3.4,
		Reviews:     23,
	  },
	  {
		Name:        "Organic Wheat Seeds",
		Category:    "Fertilizers",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       3679.56,
		Stock:       67,
		ImageURL:    "/images/products/product-938.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      4.2,
		Reviews:     494,
	  },
	  {
		Name:        "Eco-Friendly Wheat Seeds",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       1559.78,
		Stock:       858,
		ImageURL:    "/images/products/product-939.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      4.2,
		Reviews:     416,
	  },
	  {
		Name:        "High-Yield Garden Tools",
		Category:    "Tools",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       3526.02,
		Stock:       862,
		ImageURL:    "/images/products/product-940.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      2.0,
		Reviews:     280,
	  },
	  {
		Name:        "Organic Garden Tools",
		Category:    "Seeds",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       1335.86,
		Stock:       285,
		ImageURL:    "/images/products/product-941.jpg",
		Brand:       "GrowMore",
		Unit:        "Kg",
		Rating:      4.2,
		Reviews:     111,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Fertilizers",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       4881.63,
		Stock:       732,
		ImageURL:    "/images/products/product-942.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      3.1,
		Reviews:     363,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Tools",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       1946.37,
		Stock:       165,
		ImageURL:    "/images/products/product-943.jpg",
		Brand:       "GrowMore",
		Unit:        "100g",
		Rating:      3.7,
		Reviews:     407,
	  },
	  {
		Name:        "High-Yield Garden Tools",
		Category:    "Fertilizers",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       4569.15,
		Stock:       813,
		ImageURL:    "/images/products/product-944.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      2.3,
		Reviews:     40,
	  },
	  {
		Name:        "Advanced Rice Seeds",
		Category:    "Seeds",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       4184.06,
		Stock:       209,
		ImageURL:    "/images/products/product-945.jpg",
		Brand:       "GrowMore",
		Unit:        "Set",
		Rating:      1.3,
		Reviews:     354,
	  },
	  {
		Name:        "Organic Rice Seeds",
		Category:    "Fertilizers",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       2522.89,
		Stock:       582,
		ImageURL:    "/images/products/product-946.jpg",
		Brand:       "FarmPro",
		Unit:        "Kg",
		Rating:      4.8,
		Reviews:     487,
	  },
	  {
		Name:        "High-Yield Tomato Seeds",
		Category:    "Seeds",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       621.23,
		Stock:       556,
		ImageURL:    "/images/products/product-947.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      1.1,
		Reviews:     200,
	  },
	  {
		Name:        "Eco-Friendly Rice Seeds",
		Category:    "Fertilizers",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       3607.62,
		Stock:       599,
		ImageURL:    "/images/products/product-948.jpg",
		Brand:       "SeedCo",
		Unit:        "50kg",
		Rating:      1.5,
		Reviews:     224,
	  },
	  {
		Name:        "Eco-Friendly Maize Seeds",
		Category:    "Seeds",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4599.73,
		Stock:       263,
		ImageURL:    "/images/products/product-949.jpg",
		Brand:       "GrowMore",
		Unit:        "Set",
		Rating:      2.3,
		Reviews:     9,
	  },
	  {
		Name:        "Organic NPK Fertilizer",
		Category:    "Pesticides",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       1596.21,
		Stock:       553,
		ImageURL:    "/images/products/product-950.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      1.3,
		Reviews:     387,
	  },
	  {
		Name:        "High-Yield Potato Seeds",
		Category:    "Pesticides",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       4412.80,
		Stock:       238,
		ImageURL:    "/images/products/product-951.jpg",
		Brand:       "Pioneer",
		Unit:        "50kg",
		Rating:      4.2,
		Reviews:     61,
	  },
	  {
		Name:        "Eco-Friendly Garden Tools",
		Category:    "Fertilizers",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       4707.19,
		Stock:       955,
		ImageURL:    "/images/products/product-952.jpg",
		Brand:       "FarmPro",
		Unit:        "Kg",
		Rating:      4.6,
		Reviews:     46,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Pesticides",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2414.38,
		Stock:       491,
		ImageURL:    "/images/products/product-953.jpg",
		Brand:       "SeedCo",
		Unit:        "100g",
		Rating:      2.3,
		Reviews:     441,
	  },
	  {
		Name:        "Eco-Friendly Maize Seeds",
		Category:    "Seeds",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       4469.32,
		Stock:       504,
		ImageURL:    "/images/products/product-954.jpg",
		Brand:       "Pioneer",
		Unit:        "Set",
		Rating:      4.8,
		Reviews:     162,
	  },
	  {
		Name:        "Eco-Friendly Potato Seeds",
		Category:    "Fertilizers",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4820.57,
		Stock:       600,
		ImageURL:    "/images/products/product-955.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      1.4,
		Reviews:     6,
	  },
	  {
		Name:        "Eco-Friendly Rice Seeds",
		Category:    "Fertilizers",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4511.67,
		Stock:       269,
		ImageURL:    "/images/products/product-956.jpg",
		Brand:       "FarmPro",
		Unit:        "5L",
		Rating:      3.9,
		Reviews:     495,
	  },
	  {
		Name:        "Organic Potato Seeds",
		Category:    "Seeds",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       4386.97,
		Stock:       876,
		ImageURL:    "/images/products/product-957.jpg",
		Brand:       "SeedCo",
		Unit:        "Set",
		Rating:      4.3,
		Reviews:     412,
	  },
	  {
		Name:        "Organic Maize Seeds",
		Category:    "Fertilizers",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       2408.73,
		Stock:       914,
		ImageURL:    "/images/products/product-958.jpg",
		Brand:       "GrowMore",
		Unit:        "Kg",
		Rating:      3.2,
		Reviews:     389,
	  },
	  {
		Name:        "Premium Potato Seeds",
		Category:    "Tools",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       190.96,
		Stock:       528,
		ImageURL:    "/images/products/product-959.jpg",
		Brand:       "GrowMore",
		Unit:        "Set",
		Rating:      2.6,
		Reviews:     336,
	  },
	  {
		Name:        "Organic Tomato Seeds",
		Category:    "Pesticides",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       2964.48,
		Stock:       401,
		ImageURL:    "/images/products/product-960.jpg",
		Brand:       "FarmPro",
		Unit:        "50kg",
		Rating:      1.2,
		Reviews:     305,
	  },
	  {
		Name:        "Advanced NPK Fertilizer",
		Category:    "Pesticides",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       641.50,
		Stock:       816,
		ImageURL:    "/images/products/product-961.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      1.3,
		Reviews:     374,
	  },
	  {
		Name:        "Organic Potato Seeds",
		Category:    "Tools",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       3416.00,
		Stock:       753,
		ImageURL:    "/images/products/product-962.jpg",
		Brand:       "GrowMore",
		Unit:        "50kg",
		Rating:      4.0,
		Reviews:     30,
	  },
	  {
		Name:        "Eco-Friendly Tomato Seeds",
		Category:    "Pesticides",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       2233.71,
		Stock:       364,
		ImageURL:    "/images/products/product-963.jpg",
		Brand:       "Pioneer",
		Unit:        "Set",
		Rating:      4.9,
		Reviews:     45,
	  },
	  {
		Name:        "Premium Wheat Seeds",
		Category:    "Fertilizers",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       2785.80,
		Stock:       339,
		ImageURL:    "/images/products/product-964.jpg",
		Brand:       "FarmPro",
		Unit:        "50kg",
		Rating:      1.2,
		Reviews:     100,
	  },
	  {
		Name:        "High-Yield NPK Fertilizer",
		Category:    "Tools",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       2567.79,
		Stock:       27,
		ImageURL:    "/images/products/product-965.jpg",
		Brand:       "Pioneer",
		Unit:        "Kg",
		Rating:      4.7,
		Reviews:     196,
	  },
	  {
		Name:        "Premium Garden Tools",
		Category:    "Tools",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       460.75,
		Stock:       598,
		ImageURL:    "/images/products/product-966.jpg",
		Brand:       "Pioneer",
		Unit:        "100g",
		Rating:      1.1,
		Reviews:     46,
	  },
	  {
		Name:        "Eco-Friendly Wheat Seeds",
		Category:    "Pesticides",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       711.22,
		Stock:       614,
		ImageURL:    "/images/products/product-967.jpg",
		Brand:       "GrowMore",
		Unit:        "50kg",
		Rating:      1.7,
		Reviews:     365,
	  },
	  {
		Name:        "Premium Rice Seeds",
		Category:    "Tools",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       3715.83,
		Stock:       545,
		ImageURL:    "/images/products/product-968.jpg",
		Brand:       "GrowMore",
		Unit:        "5L",
		Rating:      1.8,
		Reviews:     77,
	  },
	  {
		Name:        "Eco-Friendly Organic Pesticide",
		Category:    "Fertilizers",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       568.15,
		Stock:       959,
		ImageURL:    "/images/products/product-969.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      3.9,
		Reviews:     292,
	  },
	  {
		Name:        "Premium Wheat Seeds",
		Category:    "Pesticides",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       4504.06,
		Stock:       415,
		ImageURL:    "/images/products/product-970.jpg",
		Brand:       "Pioneer",
		Unit:        "100g",
		Rating:      4.4,
		Reviews:     86,
	  },
	  {
		Name:        "Eco-Friendly Garden Tools",
		Category:    "Tools",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2611.76,
		Stock:       511,
		ImageURL:    "/images/products/product-971.jpg",
		Brand:       "EcoGuard",
		Unit:        "Kg",
		Rating:      4.6,
		Reviews:     101,
	  },
	  {
		Name:        "Eco-Friendly Tomato Seeds",
		Category:    "Seeds",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       4050.24,
		Stock:       389,
		ImageURL:    "/images/products/product-972.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      1.5,
		Reviews:     493,
	  },
	  {
		Name:        "Premium Organic Pesticide",
		Category:    "Tools",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       1773.91,
		Stock:       462,
		ImageURL:    "/images/products/product-973.jpg",
		Brand:       "FarmPro",
		Unit:        "5L",
		Rating:      1.7,
		Reviews:     434,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Seeds",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       4520.56,
		Stock:       643,
		ImageURL:    "/images/products/product-974.jpg",
		Brand:       "GrowMore",
		Unit:        "Set",
		Rating:      2.7,
		Reviews:     285,
	  },
	  {
		Name:        "Premium Garden Tools",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       3415.20,
		Stock:       427,
		ImageURL:    "/images/products/product-975.jpg",
		Brand:       "SeedCo",
		Unit:        "50kg",
		Rating:      1.7,
		Reviews:     396,
	  },
	  {
		Name:        "Organic NPK Fertilizer",
		Category:    "Fertilizers",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       921.97,
		Stock:       24,
		ImageURL:    "/images/products/product-976.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      1.1,
		Reviews:     235,
	  },
	  {
		Name:        "High-Yield Rice Seeds",
		Category:    "Seeds",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       4488.70,
		Stock:       870,
		ImageURL:    "/images/products/product-977.jpg",
		Brand:       "Pioneer",
		Unit:        "5L",
		Rating:      2.7,
		Reviews:     231,
	  },
	  {
		Name:        "Premium Maize Seeds",
		Category:    "Tools",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2435.83,
		Stock:       460,
		ImageURL:    "/images/products/product-978.jpg",
		Brand:       "SeedCo",
		Unit:        "Set",
		Rating:      4.4,
		Reviews:     261,
	  },
	  {
		Name:        "Premium NPK Fertilizer",
		Category:    "Tools",
		Description: "High-yield Hybrid Seeds Suitable For Various Climates.",
		Price:       3768.24,
		Stock:       602,
		ImageURL:    "/images/products/product-979.jpg",
		Brand:       "EcoGuard",
		Unit:        "50kg",
		Rating:      1.5,
		Reviews:     127,
	  },
	  {
		Name:        "Premium Wheat Seeds",
		Category:    "Seeds",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       2467.15,
		Stock:       787,
		ImageURL:    "/images/products/product-980.jpg",
		Brand:       "Pioneer",
		Unit:        "100g",
		Rating:      3.6,
		Reviews:     294,
	  },
	  {
		Name:        "Premium Potato Seeds",
		Category:    "Fertilizers",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       117.65,
		Stock:       935,
		ImageURL:    "/images/products/product-981.jpg",
		Brand:       "Pioneer",
		Unit:        "50kg",
		Rating:      1.4,
		Reviews:     191,
	  },
	  {
		Name:        "Organic Organic Pesticide",
		Category:    "Seeds",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       250.88,
		Stock:       290,
		ImageURL:    "/images/products/product-982.jpg",
		Brand:       "EcoGuard",
		Unit:        "5L",
		Rating:      2.1,
		Reviews:     330,
	  },
	  {
		Name:        "High-Yield Maize Seeds",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       1042.36,
		Stock:       27,
		ImageURL:    "/images/products/product-983.jpg",
		Brand:       "FarmPro",
		Unit:        "50kg",
		Rating:      3.2,
		Reviews:     137,
	  },
	  {
		Name:        "Organic Tomato Seeds",
		Category:    "Tools",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4703.70,
		Stock:       658,
		ImageURL:    "/images/products/product-984.jpg",
		Brand:       "SeedCo",
		Unit:        "50kg",
		Rating:      1.5,
		Reviews:     264,
	  },
	  {
		Name:        "Premium Garden Tools",
		Category:    "Pesticides",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       1334.76,
		Stock:       34,
		ImageURL:    "/images/products/product-985.jpg",
		Brand:       "EcoGuard",
		Unit:        "Set",
		Rating:      4.8,
		Reviews:     485,
	  },
	  {
		Name:        "Eco-Friendly NPK Fertilizer",
		Category:    "Pesticides",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       1815.18,
		Stock:       808,
		ImageURL:    "/images/products/product-986.jpg",
		Brand:       "FarmPro",
		Unit:        "Set",
		Rating:      2.0,
		Reviews:     58,
	  },
	  {
		Name:        "Premium Wheat Seeds",
		Category:    "Fertilizers",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2361.68,
		Stock:       909,
		ImageURL:    "/images/products/product-987.jpg",
		Brand:       "Pioneer",
		Unit:        "100g",
		Rating:      2.1,
		Reviews:     254,
	  },
	  {
		Name:        "Advanced Organic Pesticide",
		Category:    "Fertilizers",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       2115.61,
		Stock:       149,
		ImageURL:    "/images/products/product-988.jpg",
		Brand:       "SeedCo",
		Unit:        "5L",
		Rating:      4.8,
		Reviews:     105,
	  },
	  {
		Name:        "Premium NPK Fertilizer",
		Category:    "Fertilizers",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       2516.58,
		Stock:       798,
		ImageURL:    "/images/products/product-989.jpg",
		Brand:       "Pioneer",
		Unit:        "100g",
		Rating:      1.5,
		Reviews:     131,
	  },
	  {
		Name:        "Advanced Wheat Seeds",
		Category:    "Tools",
		Description: "Complete Set Of Essential Garden Tools.",
		Price:       2104.91,
		Stock:       586,
		ImageURL:    "/images/products/product-990.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      4.6,
		Reviews:     190,
	  },
	  {
		Name:        "Advanced NPK Fertilizer",
		Category:    "Pesticides",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       3755.02,
		Stock:       399,
		ImageURL:    "/images/products/product-991.jpg",
		Brand:       "EcoGuard",
		Unit:        "100g",
		Rating:      2.9,
		Reviews:     143,
	  },
	  {
		Name:        "Advanced Organic Pesticide",
		Category:    "Seeds",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       3640.18,
		Stock:       143,
		ImageURL:    "/images/products/product-992.jpg",
		Brand:       "Pioneer",
		Unit:        "Kg",
		Rating:      1.5,
		Reviews:     390,
	  },
	  {
		Name:        "Organic Wheat Seeds",
		Category:    "Tools",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       4305.84,
		Stock:       770,
		ImageURL:    "/images/products/product-993.jpg",
		Brand:       "EcoGuard",
		Unit:        "5L",
		Rating:      1.5,
		Reviews:     153,
	  },
	  {
		Name:        "Premium Potato Seeds",
		Category:    "Pesticides",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       104.56,
		Stock:       410,
		ImageURL:    "/images/products/product-994.jpg",
		Brand:       "GrowMore",
		Unit:        "50kg",
		Rating:      2.5,
		Reviews:     466,
	  },
	  {
		Name:        "Advanced Wheat Seeds",
		Category:    "Tools",
		Description: "Advanced Formula For Maximum Crop Yield.",
		Price:       2687.00,
		Stock:       674,
		ImageURL:    "/images/products/product-995.jpg",
		Brand:       "EcoGuard",
		Unit:        "5L",
		Rating:      4.8,
		Reviews:     15,
	  },
	  {
		Name:        "High-Yield Garden Tools",
		Category:    "Fertilizers",
		Description: "Balanced Fertilizer For All-purpose Use.",
		Price:       2871.94,
		Stock:       347,
		ImageURL:    "/images/products/product-996.jpg",
		Brand:       "GrowMore",
		Unit:        "100g",
		Rating:      4.3,
		Reviews:     335,
	  },
	  {
		Name:        "Advanced Tomato Seeds",
		Category:    "Pesticides",
		Description: "High-yielding Determinate Variety For Optimal Growth.",
		Price:       4533.05,
		Stock:       15,
		ImageURL:    "/images/products/product-997.jpg",
		Brand:       "EcoGuard",
		Unit:        "50kg",
		Rating:      3.4,
		Reviews:     477,
	  },
	  {
		Name:        "Advanced Wheat Seeds",
		Category:    "Tools",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       2337.17,
		Stock:       669,
		ImageURL:    "/images/products/product-998.jpg",
		Brand:       "FarmPro",
		Unit:        "Kg",
		Rating:      2.0,
		Reviews:     414,
	  },
	  {
		Name:        "High-Yield Wheat Seeds",
		Category:    "Seeds",
		Description: "Eco-friendly Solution For Sustainable Farming.",
		Price:       4028.73,
		Stock:       21,
		ImageURL:    "/images/products/product-999.jpg",
		Brand:       "FarmPro",
		Unit:        "100g",
		Rating:      4.1,
		Reviews:     9,
	  },
	  {
		Name:        "High-Yield Garden Tools",
		Category:    "Pesticides",
		Description: "Natural Pest Control Solution Safe For Organic Farming.",
		Price:       1551.37,
		Stock:       428,
		ImageURL:    "/images/products/product-1000.jpg",
		Brand:       "GrowMore",
		Unit:        "50kg",
		Rating:      3.3,
		Reviews:     256,
	  },
	}

	for _, product := range products {
		db.Create(&product)
	}
}